### ISSUE TITLE
Supporting joining verbs

### ISSUE THREAD

**Issue by asardaes** [asardaes/table.express#1]
Some idioms to consider:

- https://stackoverflow.com/a/34600831/5793905
- https://stackoverflow.com/questions/54312225/which-data-table-syntax-for-left-join-one-column-to-prefer
- https://stackoverflow.com/questions/33785747/data-table-join-multiple-selected-columns-with-new-names

Additional references

- https://github.com/Rdatatable/data.table/issues/944
- https://rstudio-pubs-static.s3.amazonaws.com/52230_5ae0d25125b544caab32f75f0360e775.html
- https://www.r-bloggers.com/understanding-data-table-rolling-joins/

**Comment by asardaes** [comment]
Hey @leungi just in case you're also looking at the joining verbs, do let me know if you find inconsistencies, I think I will release the new package version some time next week.

**Comment by leungi** [comment]
Thanks for note @asardaes.

I saw your `join` scripts when I was reviewing your source code; glad it's almost ready!
