### ISSUE TITLE
unexpected failure with mutate_sd()

### ISSUE THREAD

**Issue by leungi** [asardaes/table.express#13]
This has to do with #10; `reprex` below.

```
library(table.express)
#> 
#> Attaching package: 'table.express'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(data.table)
#> Warning: package 'data.table' was built under R version 3.5.3

df <- data.frame(Month = 1:12, Year = c(2000, rep(NA, 11)))
df %>% tidyr::fill(Year)
#>    Month Year
#> 1      1 2000
#> 2      2 2000
#> 3      3 2000
#> 4      4 2000
#> 5      5 2000
#> 6      6 2000
#> 7      7 2000
#> 8      8 2000
#> 9      9 2000
#> 10    10 2000
#> 11    11 2000
#> 12    12 2000

# works
as.data.table(df) %>%
  start_expr() %>% 
  mutate_sd(.SDcols = c('Year'), zoo::na.locf(.COL)) %>%
  end_expr() %>% {
    invisible(print(.))
  }
#>     Month Year
#>  1:     1 2000
#>  2:     2 2000
#>  3:     3 2000
#>  4:     4 2000
#>  5:     5 2000
#>  6:     6 2000
#>  7:     7 2000
#>  8:     8 2000
#>  9:     9 2000
#> 10:    10 2000
#> 11:    11 2000
#> 12:    12 2000

# works
as.data.table(df) %>%
  start_expr() %>% 
  mutate_sd(.SDcols = contains('Year'), zoo::na.locf(.COL)) %>%
  end_expr() %>% {
    invisible(print(.))
  }
#>     Month Year
#>  1:     1 2000
#>  2:     2 2000
#>  3:     3 2000
#>  4:     4 2000
#>  5:     5 2000
#>  6:     6 2000
#>  7:     7 2000
#>  8:     8 2000
#>  9:     9 2000
#> 10:    10 2000
#> 11:    11 2000
#> 12:    12 2000

# fails
as.data.table(df) %>%
  start_expr() %>% 
  mutate_sd(.SDcols = 'Year', zoo::na.locf(.COL)) %>%
  end_expr() %>% {
    invisible(print(.))
  }
#> Error in zoo::na.locf: could not find function "::"

# fails
# expected this to work since first line mutate_sd() internally has:
# .SDcols <- rlang::enquo(.SDcols)
as.data.table(df) %>%
  start_expr() %>% 
  mutate_sd(.SDcols = Year, zoo::na.locf(.COL)) %>%
  end_expr() %>% {
    invisible(print(.))
  }
#> Error in rlang::eval_tidy(.sdcols_quo): object 'Year' not found
```

**Comment by asardaes** [comment]
This unfortunately won't work because there's no easy way for me to differentiate between symbols that should be converted to strings, and symbols that after evaluation return strings, the latter of which is the current expected behavior. That means the last case is looking for a variable called `Year` that contains the selected columns

```r
year_col <- "Year"
as.data.table(df) %>%
    start_expr() %>% 
    mutate_sd(.SDcols = year_col, zoo::na.locf) %>%
    end_expr() %>% {
        invisible(print(.))
    }
```

**Comment by leungi** [comment]
Noted; asking for too much here 😝 

After all, one would use `mutate` if mutating one column anyways, and `mutate_sd` will work will multi-columns.

```
# multi-mutate
as.data.table(df) %>%
  start_expr() %>% 
  mutate_sd(.SDcols = Month:Year, .(zoo::na.locf(.COL))) %>%
  end_expr() %>% {
    invisible(print(.))
  }

# single mutate
as.data.table(df) %>%
  start_expr() %>% 
  mutate(Year = zoo::na.locf(Year)) %>%
  end_expr() %>% {
    invisible(print(.))
  }
```

**Comment by asardaes** [comment]
I feel like it's worth mentioning that you should avoid specifying `.COL` whenever possible, since it will simplify the expressions. I will add some information about this in the vignette, but it's relevant to, for instance, #12.

**Comment by leungi** [comment]
Point taken; thanks!

I'm sure I'll get caught again one of these days; got to learn it the hard way, I suppose.

I've started to migrate some production code to `table.express`; ~5x speed improvement on average! 🙇

**Comment by asardaes** [comment]
I've added the information at the end of the vignette. I think tomorrow I'll check some documentation consistency and push the new version to CRAN.

**Comment by leungi** [comment]
👍

**Comment by asardaes** [comment]
I'll reopen this to remind myself to check consistency of these things, or at least document it.

**Comment by asardaes** [comment]
I think this is already somewhat consistent. Verbs that have `.SDcols` accept characters, variable names, `tidyselect` calls, and `.COL` predicates; `mutate_join` is a bit of an exception. None accept single symbols in `.SDcols`, that's usually supported through the ellipsis.
