### ISSUE TITLE
Transmutation vs selection regarding efficiency

### ISSUE THREAD

**Issue by leungi** [asardaes/table.express#18]
Reprex below.

Related to #6; goal is to mimic `dplyr` behaviour and retain `group_by` on filter.

Maybe I'm overly obsessed in avoiding `select` 😛.

``` r

# install latest version
# devtools::install_github('asardaes/table.express')

suppressMessages(library(dplyr))
suppressMessages(library(table.express))
suppressMessages(library(data.table))
#> Warning: package 'data.table' was built under R version 3.5.3

## Create a data table
DT <- data.table(V1 = rep(c(1L, 2L), 5)[-10],
                 V2 = 1:9,
                 V3 = c(0.5, 1.0, 1.5),
                 V4 = rep(LETTERS[1:3], 3))

## Create a data frame (tibble)
DF <- tibble(V1 = rep(c(1L, 2L), 5)[-10],
             V2 = 1:9,
             V3 = rep(c(0.5, 1.0, 1.5), 3),
             V4 = rep(LETTERS[1:3], 3))

DF %>%
  group_by(V4) %>% 
  filter(V2 == V2[which.min(V2)])
#> # A tibble: 3 x 4
#> # Groups:   V4 [3]
#>      V1    V2    V3 V4   
#>   <int> <int> <dbl> <chr>
#> 1     1     1   0.5 A    
#> 2     2     2   1   B    
#> 3     1     3   1.5 C

DT %>%
  start_expr() %>%
  group_by(V4) %>%
  filter(V2 == V2[which.min(V2)]) %>% 
  end_expr() %>% {
    invisible(print(.))
  }
#> Warning in `[.data.table`(.DT_, V2 == V2[which.min(V2)], , by = list(V4)):
#> Ignoring by= because j= is not supplied
#>    V1 V2  V3 V4
#> 1:  1  1 0.5  A

# workaround 1
DT %>%
  start_expr() %>% 
  order_by(V2) %>%
  group_by(V4) %>%
  select(.SD[1]) %>% 
  end_expr() %>% {
    invisible(print(.))
  }
#>    V4 V1 V2  V3
#> 1:  A  1  1 0.5
#> 2:  B  2  2 1.0
#> 3:  C  1  3 1.5

# workaround 2
DT %>%
  start_expr() %>% 
  group_by(V4) %>%
  select(.SD[which.min(V2)]) %>% 
  end_expr() %>% {
    invisible(print(.))
  }
#>    V4 V1 V2  V3
#> 1:  A  1  1 0.5
#> 2:  B  2  2 1.0
#> 3:  C  1  3 1.5
```

<sup>Created on 2019-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by asardaes** [comment]
I'll copy my e-mail answer here for reference.

You can think of the topic of deep copies this way: for a `DT[i, j, ...]` call, `data.table` exposes certain variables during the evaluation of `j` (which variables it exposes depends on whether you use special symbols like `.SD` or just certain columns), but these exposed variables are **not** yet copied during the evaluation. Whatever is *returned* by the evaluation of `j` is what must be copied into the new table. I advised against using `select` in the same way as in `dplyr` because if you do something like `DT[, V2:V3]`, the output of evaluating `j` doesn't change the exposed variables at all, but they still need to be copied for the new table, so you're probably better off removing undesired variables by reference.

As soon as your output is not simply a mirror of your input, you'll need some sort of copy, so you don't need to worry about which verb would be better anymore. In this example, if `data.table` sees `DT[, .SD[which.min(V2)], by = V4]`, it will expose `.SD` and `V2`, but the output will not be the same as the input, so a copy will be needed regardless.

**Comment by leungi** [comment]
Noted; I just replied to your insightful email.

Let's stick with `data.table` philosophy and let `filter()` operate on *i* only.

**Comment by asardaes** [comment]
I must note that, AFAIK, there are exceptions.

```r
lhs <- data.table::data.table(x = rep(c("b", "a", "c"), each = 3),
                              y = c(1, 3, 6),
                              v = 1:9)

rhs <- data.table::data.table(x = c("c", "b"),
                              v = 8:7,
                              foo = c(4, 2))

lhs %>%
    start_expr %>%
    right_join(rhs, x) %>%
    select(v = i.v, y = mean(y)) %>%
    frame_append(by = .EACHI) %T>%
    print %>%
    end_expr
.DT_[rhs, .select_matching(.SD, v = i.v, y = mean(y), .negate = FALSE), 
    on = list(x), by = .EACHI]
   x v        y
1: c 8 3.333333
2: b 7 3.333333

lhs %>%
    start_expr %>%
    right_join(rhs, x) %>%
    transmute(v = i.v, y = mean(y)) %>%
    frame_append(by = .EACHI) %T>%
    print %>%
    end_expr
.DT_[rhs, list(v = i.v, y = mean(y)), on = list(x), by = .EACHI]
   x v        y
1: c 8 3.333333
2: b 7 3.333333
```

Both shown calls work the same, but the expression built with `select` specifies `.SD`, and I believe building and exposing `.SD` does require considerable time; see for example Rdatatable/data.table#613.

I'll keep this open until I add this info to the vignette.

**Comment by asardaes** [comment]
I think I managed to work around the special case mentioned above. When `select` delegates to `.select_matching`, it will leave `.SD` missing in some cases.

**Comment by asardaes** [comment]
I think the workaround should be enough for now. Regarding the original questions, I've added `max_by` and `min_by` in 5e012f9e483354148bf7e07985bed38b56da66d6

**Comment by leungi** [comment]
Nicely done; the `.some` argument is very thoughtful!

And I noticed `start_`/`end_expr()` is now optional 👏 

``` r
suppressMessages(library(dplyr))
suppressMessages(library(table.express))
suppressMessages(library(data.table))
#> Warning: package 'data.table' was built under R version 3.5.3
# > Warning: package 'data.table' was built under R version 3.5.3

## Create a data table
DT <- data.table(
  V1 = rep(c(1L, 2L), 5)[-10],
  V2 = 1:9,
  V3 = c(0.5, 1.0, 1.5),
  V4 = rep(LETTERS[1:3], 3)
)

## Create a data frame (tibble)
DF <- tibble(
  V1 = rep(c(1L, 2L), 5)[-10],
  V2 = 1:9,
  V3 = rep(c(0.5, 1.0, 1.5), 3),
  V4 = rep(LETTERS[1:3], 3)
)

DF %>%
  group_by(V4) %>%
  filter(
    V2 == V2[which.min(V2)],
    V1 == V1[which.min(V1)]
  )
#> # A tibble: 2 x 4
#> # Groups:   V4 [2]
#>      V1    V2    V3 V4   
#>   <int> <int> <dbl> <chr>
#> 1     1     1   0.5 A    
#> 2     1     3   1.5 C

DT %>%
  min_by(c("V2", "V1"), V4)
#>    V1 V2  V3 V4
#> 1:  1  1 0.5  A
#> 2:  1  3 1.5  C
```

<sup>Created on 2019-07-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
