### ISSUE TITLE
select() with combination of tidyselect helpers

### ISSUE THREAD

**Issue by leungi** [asardaes/table.express#4]
First, I'd like to thank you for this package!

As a `tidyverse` user converting to `data.table`, this makes the transition much smoother 😄 

Below is a reprex; this operation is one I find it troublesome to use in `data.table`, without having to rename the columns manually after.

``` r
library(table.express)
#> Warning: package 'table.express' was built under R version 3.5.3
#> 
#> Attaching package: 'table.express'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(data.table)
#> Warning: package 'data.table' was built under R version 3.5.3
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:data.table':
#> 
#>     between, first, last
#> The following object is masked from 'package:table.express':
#> 
#>     order_by
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# intended result
mtcars %>% 
  select(mpg, hp:vs) %>% 
  head
#>                    mpg  hp drat    wt  qsec vs
#> Mazda RX4         21.0 110 3.90 2.620 16.46  0
#> Mazda RX4 Wag     21.0 110 3.90 2.875 17.02  0
#> Datsun 710        22.8  93 3.85 2.320 18.61  1
#> Hornet 4 Drive    21.4 110 3.08 3.215 19.44  1
#> Hornet Sportabout 18.7 175 3.15 3.440 17.02  0
#> Valiant           18.1 105 2.76 3.460 20.22  1

# unexpected result
DT <- mtcars %>%
  as.data.table

DT %>%
  start_expr %>%
  select(mpg, hp:vs) %>%
  end_expr %>% 
  head
#> Warning in hp:vs: numerical expression has 32 elements: only the first used
#> Warning in hp:vs: numerical expression has 32 elements: only the first used
#> Warning in as.data.table.list(jval): Item 1 is of size 32 but maximum size
#> is 111 (recycled leaving a remainder of 15 items)
#>     mpg  V2
#> 1: 21.0 110
#> 2: 21.0 109
#> 3: 22.8 108
#> 4: 21.4 107
#> 5: 18.7 106
#> 6: 18.1 105
```

<sup>Created on 2019-06-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by asardaes** [comment]
Hello, I'm glad you found it useful.

The core problem here is that `data.table` doesn't support that syntax, so writing something like `DT[, .(mpg, hp:vs)]` doesn't work either. I tried to avoid post-processing where possible, so that expression is the one that is currently built, and I'd have to "expand" the `hp:vs` part eagerly if I wanted to work around it. It's doable, but it would end up being another special eager case. I'll play around with the idea, see if it's not too ugly to implement.

**Comment by asardaes** [comment]
Hey @leungi, I found a way to do this without making it eager. If you can [install from GitHub](https://rdrr.io/cran/remotes/man/install_github.html) give it a try and let me know how it works for you.

**Comment by leungi** [comment]
Perfect timing! I've been practising with your package since morning.

Tested and working like magic; thanks for the rapid enhancement 👍
