### ISSUE TITLE
Allow negation in select()

### ISSUE THREAD

**Issue by leungi** [asardaes/table.express#9]
Reprex below.

``` r
library(dplyr)
library(table.express)
library(data.table)

DT <- data.table(V1 = rep(c(1L, 2L), 5)[-10],
                 V2 = 1:9,
                 V3 = c(0.5, 1.0, 1.5),
                 V4 = rep(LETTERS[1:3], 3))

cols <- c("V2", "V3")

# intention - exclude columns
DT[, !c("V2", "V3")]
#>    V1 V4
#> 1:  1  A
#> 2:  2  B
#> 3:  1  C
#> 4:  2  A
#> 5:  1  B
#> 6:  2  C
#> 7:  1  A
#> 8:  2  B
#> 9:  1  C

# none of the options work
DT %>%
  start_expr() %>% 
  select(-one_of(cols)) %>%
  # select(!one_of(cols)) %>%
  # select(-!!!cols, .parse = TRUE) %>%
  end_expr() %>% {
    invisible(print(.))
  }
#>    V1
#> 1: -2
#> 2: -3
```

<sup>Created on 2019-06-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by asardaes** [comment]
This one would be tricky to implement, lots of special cases, and since the columns that remain selected are still copied, you could do:

```r
ans <- DT %>%
    copy %>%
    start_expr %>%
    mutate_sd(NULL, .SDcols = cols) %>%
    end_expr
```

Simply removing `copy` if you don't mind removing from `DT` by reference.

It might still be worth adding at least support for `!`, since `select` statements after joins could benefit from it.

**Comment by asardaes** [comment]
The easiest way (implementation-wise) that I could think of was to add a `.negate` parameter. This means we can still use all the normal expressions (including `tidyselect` helpers), but we can only negate all or none.

**Comment by leungi** [comment]
Once again, forgot about `data.table` built-in `:= NULL` syntax to drop columns; good move.

Including a `.negate` is a good idea, and the negate-all-or-none behaviour is acceptable given the below:

``` r
library(dplyr)

DF <- tibble(V1 = rep(c(1L, 2L), 5)[-10],
             V2 = 1:9,
             V3 = rep(c(0.5, 1.0, 1.5), 3),
             V4 = rep(LETTERS[1:3], 3))

# doesn't matter what's after -V1, select() honours the negation only
DF %>% select(-V1, V3)
#> # A tibble: 9 x 3
#>      V2    V3 V4   
#>   <int> <dbl> <chr>
#> 1     1   0.5 A    
#> 2     2   1   B    
#> 3     3   1.5 C    
#> 4     4   0.5 A    
#> 5     5   1   B    
#> 6     6   1.5 C    
#> 7     7   0.5 A    
#> 8     8   1   B    
#> 9     9   1.5 C
```

Also, I realized the following:

- `mutate_sd()` can act as all of `mutate_*` variants
- `transmute_sd()` can act as all of `summarise_*` variants

If you're revamping `select()`, I wonder if it's more sustainable to create a `select_sd()` to cover `select_*` variants, and also contains all the extra powers that comes with `table.express` compared to `dplyr::select`.

**Comment by asardaes** [comment]
I wonder if `select` isn't too convenient already 😛. If users want to avoid copies, they will have to mostly avoid `select` anyway (except after joins). The `select_*` scoped variants from `dplyr` seem to be mostly to rename while selecting, and I wouldn't be able to avoid copies if I wanted to implement something similar.

From those, `select_if` is one that sounds interesting, but with the recent modifications to `mutate_sd`, it might be preferable to change something like 

```r
select_if(mtcars, ~ all(. %% 1 == 0))
```

to 

```r
as.data.table(mtcars) %>%
  start_expr %>%
  mutate_sd(!all(.COL %% 1 == 0), NULL) %>%
  end_expr
```

which is quite a bit more verbose, but not much I can do about that right now.

After releasing 0.2.0 it might be worth doing something like a cookbook showing common `dplyr` operations and their equivalents in `table.express`, describing things like the aforementioned.

**Comment by leungi** [comment]
True that most `select_*` variants are for renaming, which was I was after I guess 😊.

If we ignore the renaming use of `select_*`, I agree the current `mutate_sd` is sufficiently useful!

```
DT <- data.table(V1 = rep(c(1L, 2L), 5)[-10],
                 V2 = 1:9,
                 V3 = c(0.5, 1.0, 1.5),
                 V4 = rep(LETTERS[1:3], 3))

# make use of data.table drop column syntax with := NULL
DT %>%
    start_expr %>%
    mutate_sd(!is.integer(.COL), NULL) %>%
    end_expr

# same as above in dplyr syntax
DF <- tibble(V1 = rep(c(1L, 2L), 5)[-10],
             V2 = 1:9,
             V3 = rep(c(0.5, 1.0, 1.5), 3),
             V4 = rep(LETTERS[1:3], 3))

DF %>% select_if(is.integer)
```

I'm actually training myself on `table.express` against several popular dplyr-to-data.table blogs, so the least I can do for your amazing work is to share them with you, to add to your `pkgdown` site.

Here are the blogs used:

- http://franknarf1.github.io/r-tutorial/_book/tables.html#tables
- https://atrebas.github.io/post/2019-03-03-datatable-dplyr/
- https://suzan.rbind.io/categories/tutorial/

To close, having `.negate` in `select` is still a good idea; this way, `dplyr` users will have less mindset adjustments to make (i.e., use `mutate_sd` as a hack).

**Comment by asardaes** [comment]
Thanks! That should definitely come in handy.

**Comment by leungi** [comment]
`.negate` is a nice touch!

``` r

# install latest version
# devtools::install_github('asardaes/table.express')

library(dplyr)
library(table.express)
library(data.table)

## Create a data table
DT <- data.table(V1 = rep(c(1L, 2L), 5)[-10],
                 V2 = 1:9,
                 V3 = c(0.5, 1.0, 1.5),
                 V4 = rep(LETTERS[1:3], 3))

# table.express
DT %>%
  start_expr() %>% 
  select(V2:V3, .negate = TRUE) %>% 
  end_expr() %>% {
    invisible(print(.))
  }
#>    V1 V4
#> 1:  1  A
#> 2:  2  B
#> 3:  1  C
#> 4:  2  A
#> 5:  1  B
#> 6:  2  C
#> 7:  1  A
#> 8:  2  B
#> 9:  1  C

# dplyr
as.data.frame(DT) %>% 
  select(-(V2:V3))
#>   V1 V4
#> 1  1  A
#> 2  2  B
#> 3  1  C
#> 4  2  A
#> 5  1  B
#> 6  2  C
#> 7  1  A
#> 8  2  B
#> 9  1  C
```

<sup>Created on 2019-07-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
